<a href="https://colab.research.google.com/github/janani-tamilarasan/Python-Problems/blob/main/2_b_Dataframes_using_dicitionay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Create 3 Dataframe using dictionaries
 - A DataFrame is a 2-dimensional table

In [4]:
# Example 1 - Customer Data

import pandas as pd

data = {
     'Ids': [1,2,3],
     'Firstname':['Janani','Swamynathan','Vishwa'],
     'Lastname': ['Tamilarsan','Selvaraj','Swamynathan'],
     'Mobile': [00000000,None,None],
     'Email': ['janani@gmail.com','tst@gm.com','swany@gm.co'],
     'dob':  ['21/05/1990',None,'1/2/1984']
}

customer_data = pd.DataFrame(data)
customer_data

   Ids    Firstname     Lastname  Mobile             Email         dob
0    1       Janani   Tamilarsan     0.0  janani@gmail.com  21/05/1990
1    2  Swamynathan     Selvaraj     NaN        tst@gm.com        None
2    3       Vishwa  Swamynathan     NaN       swany@gm.co    1/2/1984

In [10]:
# Example 2 - Products Data

import pandas as pd

data = {
     'ProductIds': [1,2,3],
     'ProdcutName':['Refirgerator','Washing Machine','Laptop'],
     'Qty': [2,1,0],
     'Dealer': ['Samsung','LG', 'HP'],
     'Stars':[None,None,3]
}

product_data = pd.DataFrame(data)
product_data

   ProductIds      ProdcutName  Qty   Dealer  Stars
0           1     Refirgerator    2  Samsung    NaN
1           2  Washing Machine    1       LG    NaN
2           3           Laptop    0       HP    3.0

In [12]:
# Example 3 - order Data

import pandas as pd

data = {
     'ProductIds': [1,2,3],
     'OrderIds':[1,22,33],
     'CustomerIds': [1,2,2],
     'Status': ['Delivered','Refund Initiated', 'Shipped'],
}

orders = pd.DataFrame(data)
orders

   ProductIds  OrderIds  CustomerIds            Status
0           1         1            1         Delivered
1           2        22            2  Refund Initiated
2           3        33            2           Shipped